apiVersion: v1
kind: Service
metadata:
    name: rails-app-service
spec:
  selector:
    app: rails-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
